import { gcm } from '@noble/ciphers/aes.js';
import { randomBytes, utf8ToBytes, bytesToUtf8, concatBytes } from '@noble/ciphers/utils.js';
import { pbkdf2 } from '@noble/hashes/pbkdf2.js';
import { sha256 } from '@noble/hashes/sha2.js';

/**
 * Password-protected QR payloads. Uses AES-256-GCM (authenticated encryption)
 * from the audited, dependency-free @noble/ciphers — no custom crypto. The key
 * is derived from the password with PBKDF2-SHA256. Everything runs on-device;
 * no plaintext or password leaves the app.
 *
 * Wire format (all binary, then base64, prefixed with a marker):
 *   SQR2: base64( iterations[4 BE] | salt[16] | nonce[12] | ciphertext+gcmTag )
 * The iteration count is stored IN the payload so a QR always decrypts with the
 * exact PBKDF2 cost it was made with — otherwise changing ITERATIONS between
 * app builds silently bricks every QR generated by an older build ("wrong
 * password" on the right password). SQR1 is the pre-versioning format that
 * omitted the count; we still read it by trying the historical dev values.
 */
const MARKER = 'SQR2:';
const LEGACY_MARKER = 'SQR1:';
const SALT_LEN = 16;
const NONCE_LEN = 12;
const KEY_LEN = 32; // AES-256
const ITER_LEN = 4; // uint32 big-endian, prepended to SQR2 payloads
// PBKDF2 runs in pure JS on Hermes (no JIT), so each iteration costs real
// wall-clock on the JS thread — 100k took 40s+ on an emulator. 10k keeps the
// derive ~1s on a real device while still adding meaningful brute-force cost
// on top of the password itself.
// ponytail: 10k is low for PBKDF2; swap to native (react-native-quick-crypto)
// to raise iterations back to 100k+ without the JS-thread cost. Safe to change
// now — the count travels with each QR, so old QRs keep working.
const ITERATIONS = 10_000;
// SQR1 QRs from earlier dev builds carry no count; try the values those builds
// shipped (cheapest first so the common case is fast). Bounds also sanity-check
// a corrupt SQR2 count so we never spin PBKDF2 on garbage.
const LEGACY_ITERATIONS = [10_000, 100_000, 150_000];
const MIN_ITER = 1_000;
const MAX_ITER = 2_000_000;

const deriveKey = (password: string, salt: Uint8Array, iterations: number) =>
  pbkdf2(sha256, utf8ToBytes(password), salt, { c: iterations, dkLen: KEY_LEN });

/** True if a decoded QR value is one of our encrypted payloads. */
export const isSecretQr = (value: string) =>
  value.startsWith(MARKER) || value.startsWith(LEGACY_MARKER);

/** Encrypt a message into a Secret-QR payload string. */
export function encryptSecret(message: string, password: string): string {
  const iter = new Uint8Array([
    (ITERATIONS >>> 24) & 0xff, (ITERATIONS >>> 16) & 0xff, (ITERATIONS >>> 8) & 0xff, ITERATIONS & 0xff,
  ]);
  const salt = randomBytes(SALT_LEN);
  const nonce = randomBytes(NONCE_LEN);
  const key = deriveKey(password, salt, ITERATIONS);
  const ct = gcm(key, nonce).encrypt(utf8ToBytes(message));
  return MARKER + bytesToBase64(concatBytes(iter, salt, nonce, ct));
}

/**
 * Decrypt a Secret-QR payload. Throws if the password is wrong or the data is
 * corrupt (GCM authentication failure) — callers surface a friendly message.
 */
export function decryptSecret(value: string, password: string): string {
  if (value.startsWith(LEGACY_MARKER)) return decryptLegacy(value, password);

  const packed = base64ToBytes(value.slice(MARKER.length));
  if (packed.length <= ITER_LEN + SALT_LEN + NONCE_LEN) throw new Error('corrupt');
  const iterations =
    packed[0] * 0x1000000 + (packed[1] << 16) + (packed[2] << 8) + packed[3];
  if (iterations < MIN_ITER || iterations > MAX_ITER) throw new Error('corrupt');
  const salt = packed.slice(ITER_LEN, ITER_LEN + SALT_LEN);
  const nonce = packed.slice(ITER_LEN + SALT_LEN, ITER_LEN + SALT_LEN + NONCE_LEN);
  const ct = packed.slice(ITER_LEN + SALT_LEN + NONCE_LEN);
  const key = deriveKey(password, salt, iterations);
  return bytesToUtf8(gcm(key, nonce).decrypt(ct));
}

/** Read a pre-versioning SQR1 payload by trying each historical iteration count. */
function decryptLegacy(value: string, password: string): string {
  const packed = base64ToBytes(value.slice(LEGACY_MARKER.length));
  if (packed.length <= SALT_LEN + NONCE_LEN) throw new Error('corrupt');
  const salt = packed.slice(0, SALT_LEN);
  const nonce = packed.slice(SALT_LEN, SALT_LEN + NONCE_LEN);
  const ct = packed.slice(SALT_LEN + NONCE_LEN);
  for (const iterations of LEGACY_ITERATIONS) {
    try {
      return bytesToUtf8(gcm(deriveKey(password, salt, iterations), nonce).decrypt(ct));
    } catch {
      // GCM auth failed for this count — try the next, else fall through to throw.
    }
  }
  throw new Error('wrong password');
}

// --- base64 for Uint8Array (Hermes has no Buffer; keep encoding self-contained) ---
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

function bytesToBase64(bytes: Uint8Array): string {
  let out = '';
  for (let i = 0; i < bytes.length; i += 3) {
    const a = bytes[i];
    const b = i + 1 < bytes.length ? bytes[i + 1] : 0;
    const c = i + 2 < bytes.length ? bytes[i + 2] : 0;
    out += B64[a >> 2] + B64[((a & 3) << 4) | (b >> 4)];
    out += i + 1 < bytes.length ? B64[((b & 15) << 2) | (c >> 6)] : '=';
    out += i + 2 < bytes.length ? B64[c & 63] : '=';
  }
  return out;
}

function base64ToBytes(str: string): Uint8Array {
  const clean = str.replace(/[^A-Za-z0-9+/]/g, '');
  const len = Math.floor((clean.length * 3) / 4);
  const out = new Uint8Array(len);
  let p = 0;
  for (let i = 0; i < clean.length; i += 4) {
    const n =
      (B64.indexOf(clean[i]) << 18) |
      (B64.indexOf(clean[i + 1]) << 12) |
      ((clean[i + 2] ? B64.indexOf(clean[i + 2]) : 0) << 6) |
      (clean[i + 3] ? B64.indexOf(clean[i + 3]) : 0);
    if (p < len) out[p++] = (n >> 16) & 0xff;
    if (p < len) out[p++] = (n >> 8) & 0xff;
    if (p < len) out[p++] = n & 0xff;
  }
  return out;
}
